---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order-service
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service-name: order-service
