apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr.io
      containers:
        - name: customer-service
          image: "ghcr.io/genekuo/lpm10252024/customer-service:0.1.0-SNAPSHOT"
