---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    name: customer-service
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    service-name: customer-service
