name: Build, test and publish

on:
  push:

jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        distribution: corretto

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false

    - name: Install K8s Kind
      run: sudo ./.github/workflows/install-k8s-tools.sh

    - name: Validate K8S manifests
      run: ./test/validate-k8s-yaml.sh

    - name: Build
      run: |
        cd application
        ./gradlew build

    - name: Create Kind Cluster
      env:
        GITHUB_USER: genekuo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export GITHUB_DOCKER_SERVER=ghcr.io/genekuo
        ./manage/create-kind-cluster.sh

    - name: Test Kind installation
      run: ./test/test-kind-cluster.sh

    - name: Install infrastructure services
      run: ./manage/install-infrastructure-services.sh

    - name: Test Kafka
      run: ./test/test-kafka.sh

    - name: Test Get JWT
      run: ./test/get-jwt.sh

    - name: Test all services
      run: |
        ./test/test-all-services.sh

    - name: Install CDC service
      run: ./manage/install-cdc-service.sh

    - name: End to end tests
      run: |
        cd application
        ./gradlew :end-to-end-tests:cleanEndToEndTest
        ./gradlew :end-to-end-tests:endToEndTestClasses

        (./gradlew --no-build-cache endToEndTestsUsingKind || ./gradlew --no-build-cache endToEndTestsUsingKind)

    - name: Undeploy services
      run: ./manage/undeploy-services.sh
    - name: Delete Kind Cluster
      run: ./manage/delete-kind-cluster.sh

    - name: Push images
      env:
        GITHUB_USER: genekuo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./manage/push-images.sh

    - name: Create Kind Cluster
      env:
        GITHUB_USER: genekuo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export GITHUB_DOCKER_SERVER=ghcr.io/genekuo
        ./manage/create-kind-cluster.sh

    - name: Install infrastructure services
      run: ./manage/install-infrastructure-services.sh

    - name: Test all services
      run: ./test/test-all-services.sh --private-registry

    - name: Save pod logs
      if: ${{ always() }}
      run: ./.github/workflows/dump-k8s.sh
      
    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          **/build/reports
          **/build/test-results

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: container-logs
        path: ~/container-logs
