name: Build, test and publish

on:
  push:

jobs:
  build-test-and-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        distribution: corretto

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-read-only: false

    - name: Build
      run: |
        cd application
        ./gradlew build

    - name: Install K8s Kind
      run: sudo ./.github/workflows/install-k8s-tools.sh

    - name: Create Kind Cluster
      run: ./manage/create-kind-cluster.sh

    - name: Test Kind installation
      run: ./test/test-kind-cluster.sh

    - name: Delete Kind Cluster
      run: ./manage/delete-kind-cluster.sh

    - name: Save test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          **/build/reports
          **/build/test-results

    - name: get container logs
      run: ./.github/workflows/print-container-logs.sh
      if: ${{ always() }}

    - name: Save container logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: container-logs
        path: ~/container-logs
